# @2023 凹语言 作者。保留所有权利。

name: MnBook
on:
  pull_request:
  push:
    branches:
      - main
      - master
      - "releases/*"
jobs:
  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - run: go version
      - run: go env

      - run: go test ./...

  Publish:
    runs-on: ubuntu-latest
    if: ${{github.repository == 'wa-lang/mnbook'}}
    needs: [Test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.WA_DEPLOY }}
