# @2023 凹语言 作者。保留所有权利。

name: waBook
on:
  pull_request:
  push:
    branches:
      - main
      - master
      - "releases/*"
jobs:
  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - run: go version
      - run: go env

      - run: go test ./...
